title: "GeoTrellis Documentation"
description: "Documentation for GeoTrellis"
keywords:
- GeoTrellis
- Documentation
- Tutorial
- GIS
- Raster
- Guide
- GeoProcessing
- Distributed
- Scalable
baseurl: 
pygments: true
permalink: /:categories/:title.html

# markdown: rdiscount
